# Change these first
owner: a-lang # Your GitHub username
repo: raida-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: RAIDA#0 Australia
    url: $RAIDA_00
  - name: RAIDA#1 Macedonia
    url: $RAIDA_01
  - name: RAIDA#2 Philippines
    url: $RAIDA_02
  - name: RAIDA#3 Serbia
    url: $RAIDA_03
  - name: RAIDA#4 Switzerland
    url: $RAIDA_04
  - name: RAIDA#5 South Korea
    url: $RAIDA_05
  - name: RAIDA#6 Japan
    url: $RAIDA_06
  - name: RAIDA#7 UK
    url: $RAIDA_07
  - name: RAIDA#8 India
    url: $RAIDA_08
  - name: RAIDA#9 India
    url: $RAIDA_09
  - name: RAIDA#10 Germany
    url: $RAIDA_10
  - name: RAIDA#11 USA
    url: $RAIDA_11
  - name: RAIDA#12 India
    url: $RAIDA_12
  - name: RAIDA#13 Taiwan
    url: $RAIDA_13
  - name: RAIDA#14 Russia
    url: $RAIDA_14
  - name: RAIDA#15 Russia
    url: $RAIDA_15
  - name: RAIDA#16 UK
    url: $RAIDA_16
  - name: RAIDA#17 Singapore
    url: $RAIDA_17
  - name: RAIDA#18 USA
    url: $RAIDA_18
  - name: RAIDA#19 Argentina
    url: $RAIDA_19
  - name: RAIDA#20 France
    url: $RAIDA_20
  - name: RAIDA#21 India
    url: $RAIDA_21
  - name: RAIDA#22 USA
    url: $RAIDA_22
  - name: RAIDA#23 Germany
    url: $RAIDA_23
  - name: RAIDA#24 Canada
    url: $RAIDA_24


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /raida-uptime
  logoUrl: https://github.com/a-lang/raida-uptime/raw/master/CloudCoinLogo2.svg
  name: RAIDA Supernodes - Uptime
  introTitle: "**RAIDA** is the **R**edundant **A**rray of **I**ndependent **D**etection **A**gents."
  introMessage: "**RAIDA** has data-supremacy like blockchain, meaning it cannot be brought down, controlled or manipulated. [**View more details about RAIDA**](https://raidatech.com/)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
